name: Generate Plots on Commit

on:
  push:
    branches:
      - main 

jobs:
  generate-plots:
    runs-on: ubuntu-latest

    steps:
    - name: Set up virtual display
      run: sudo apt-get install -y xvfb

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Start virtual display
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 &

    - name: Install dependencies
      run: |
        pip install -r requirements.txt 

    - name: Run hill_climbing.py
      run: python cartpole_env/hill_climbing.py

    - name: Run qlearning.py
      run: python cartpole_env/qlearning.py

    - name: Upload plots
      uses: actions/upload-artifact@v3
      with:
        name: Generated-Plots
        path: cartpole_env/results/ 
