name: Generate and Visualize Plots

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-plots:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    #Install a virtual display
    - name: Install Xvfb (virtual display)
      run: sudo apt-get install -y xvfb

    - name: Start Xvfb
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1024x768x24 &

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run qlearning.py
      run: |
        export DISPLAY=:99  # Ensure the virtual display is used
        python cartpole_env/qlearning.py

    # - name: Run hill_climbing.py
    #   run: |
    #     export DISPLAY=:99  # Ensure the virtual display is used
    #     python cartpole_env/hill_climbing.py

    - name: Upload plots
      uses: actions/upload-artifact@v3
      with:
        name: Generated-Plots
        path: cartpole_env/ 
    
    - name: Upload PPO Training Plot
      uses: actions/upload-artifact@v3
      with:
        name: PPO_Training_Plot
        path: cartpole_env/ppo_training.png
